services:
  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard-test
    ports:
      - "8090:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
    restart: unless-stopped

  nginx-portail:
    build: ./nginx-portal
    container_name: nginx-portail-test
    ports:
      - "8091:80"
    restart: unless-stopped

volumes:
  kanboard_data:
  kanboard_plugins:
