apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanboard-data
  namespace: mggt1103-projet
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  namespace: mggt1103-projet
  labels:
    app: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      containers:
        - name: kanboard
          image: kanboard/kanboard:latest
          ports:
            - containerPort: 80
          env:
            - name: REVERSE_PROXY_AUTH
              value: "true"
            - name: REVERSE_PROXY_USER_HEADER
              value: "HTTP_X_AUTH_REQUEST_USER"
            - name: REVERSE_PROXY_DEFAULT_ADMIN
              value: "agent1"
            - name: TRUSTED_PROXY_NETWORKS
              value: "10.42.0.0/16,10.43.0.0/16"
          volumeMounts:
            - name: data
              mountPath: /var/www/app/data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kanboard-data
---
apiVersion: v1
kind: Service
metadata:
  name: kanboard
  namespace: mggt1103-projet
spec:
  selector:
    app: kanboard
  ports:
    - port: 80
      targetPort: 80
